name = "crypto-orderbook-depth-template"
main = "worker.js"
compatibility_date = "2026-07-23"
workers_dev = true

[vars]
DEFAULT_EXCHANGE = "gate"
DEFAULT_PAIR = "EQTY_USDT"
# Use "*" for easiest setup. For production, set your own origin, e.g. "https://YOURUSER.github.io".
ALLOWED_ORIGINS = "*"
ALLOW_DIRECT = "true"
